package co.edu.utp.isc.david.prestamos.persistencia1;
// Generated 22/02/2019 01:21:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private int numPrestamo;
     private Persona persona;
     private double cantidad;
     private Date fechaDeSolicitud;
     private int estadoDeAprobacion;
     private Date fechaDeDevolucion;
     private double valorCuota;
     private int cantidadCuotas;
     private int cuotasPagadas;
     private Date proximaCuota;
     private Date fechaEntrega;
     private double saldoPendiente;

    public Prestamo() {
    }

    public Prestamo(int numPrestamo, Persona persona, double cantidad, Date fechaDeSolicitud, int estadoDeAprobacion, Date fechaDeDevolucion, double valorCuota, int cantidadCuotas, int cuotasPagadas, Date proximaCuota, Date fechaEntrega, double saldoPendiente) {
       this.numPrestamo = numPrestamo;
       this.persona = persona;
       this.cantidad = cantidad;
       this.fechaDeSolicitud = fechaDeSolicitud;
       this.estadoDeAprobacion = estadoDeAprobacion;
       this.fechaDeDevolucion = fechaDeDevolucion;
       this.valorCuota = valorCuota;
       this.cantidadCuotas = cantidadCuotas;
       this.cuotasPagadas = cuotasPagadas;
       this.proximaCuota = proximaCuota;
       this.fechaEntrega = fechaEntrega;
       this.saldoPendiente = saldoPendiente;
    }
   
    public int getNumPrestamo() {
        return this.numPrestamo;
    }
    
    public void setNumPrestamo(int numPrestamo) {
        this.numPrestamo = numPrestamo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaDeSolicitud() {
        return this.fechaDeSolicitud;
    }
    
    public void setFechaDeSolicitud(Date fechaDeSolicitud) {
        this.fechaDeSolicitud = fechaDeSolicitud;
    }
    public int getEstadoDeAprobacion() {
        return this.estadoDeAprobacion;
    }
    
    public void setEstadoDeAprobacion(int estadoDeAprobacion) {
        this.estadoDeAprobacion = estadoDeAprobacion;
    }
    public Date getFechaDeDevolucion() {
        return this.fechaDeDevolucion;
    }
    
    public void setFechaDeDevolucion(Date fechaDeDevolucion) {
        this.fechaDeDevolucion = fechaDeDevolucion;
    }
    public double getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(double valorCuota) {
        this.valorCuota = valorCuota;
    }
    public int getCantidadCuotas() {
        return this.cantidadCuotas;
    }
    
    public void setCantidadCuotas(int cantidadCuotas) {
        this.cantidadCuotas = cantidadCuotas;
    }
    public int getCuotasPagadas() {
        return this.cuotasPagadas;
    }
    
    public void setCuotasPagadas(int cuotasPagadas) {
        this.cuotasPagadas = cuotasPagadas;
    }
    public Date getProximaCuota() {
        return this.proximaCuota;
    }
    
    public void setProximaCuota(Date proximaCuota) {
        this.proximaCuota = proximaCuota;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public double getSaldoPendiente() {
        return this.saldoPendiente;
    }
    
    public void setSaldoPendiente(double saldoPendiente) {
        this.saldoPendiente = saldoPendiente;
    }




}


