/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.david.prestamos.presentacion.ultils;

import co.edu.utp.isc.david.prestamos.persistencia2.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Formulario_Ingreso extends javax.swing.JPanel{
    private final Controlador controlador;
    /**
     * Creates new form Formulario_Ingreso
     */
    public Formulario_Ingreso() {
        initComponents();
        controlador = Controlador.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameJL = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        fLastNJL = new javax.swing.JLabel();
        fLastNJTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        slastNJTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        movilJTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        houseJTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CancelarJB = new javax.swing.JButton();
        enviarJB = new javax.swing.JButton();
        ccJTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        nameJL.setText("Nombres *");

        nameJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameJTFKeyPressed(evt);
            }
        });

        fLastNJL.setText("Primer Apellido *");

        fLastNJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fLastNJTFActionPerformed(evt);
            }
        });
        fLastNJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fLastNJTFKeyPressed(evt);
            }
        });

        jLabel1.setText("Segundo Apellido *");

        slastNJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slastNJTFActionPerformed(evt);
            }
        });
        slastNJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                slastNJTFKeyPressed(evt);
            }
        });

        jLabel2.setText("Telefono Movi *");

        movilJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilJTFActionPerformed(evt);
            }
        });
        movilJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                movilJTFKeyPressed(evt);
            }
        });

        jLabel3.setText("Telefono Casa");

        houseJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                houseJTFKeyPressed(evt);
            }
        });

        jLabel4.setText("REGISTRO NUEVO CLIENTE");

        CancelarJB.setText("Cancelar");
        CancelarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarJBActionPerformed(evt);
            }
        });

        enviarJB.setText("Enviar");
        enviarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarJBActionPerformed(evt);
            }
        });

        ccJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccJTFActionPerformed(evt);
            }
        });
        ccJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccJTFKeyPressed(evt);
            }
        });

        jLabel5.setText("CC *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(289, 289, 289)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(slastNJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(houseJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(fLastNJL)
                                    .addComponent(fLastNJTF)
                                    .addComponent(movilJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(ccJTF)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(CancelarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(enviarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLastNJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(fLastNJTF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slastNJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(movilJTF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccJTF)
                    .addComponent(houseJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarJB)
                    .addComponent(enviarJB))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fLastNJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fLastNJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fLastNJTFActionPerformed

    private void slastNJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slastNJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slastNJTFActionPerformed

    private void movilJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilJTFActionPerformed

    private void enviarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarJBActionPerformed
         int cc = 0;
        try {
            cc = Integer.parseInt(ccJTF.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "EL valor Cedula no es correcto\n"
                    + "Recuerda que solo se admiten valores numericos sin espacios entre ellos", "Error", JOptionPane.ERROR_MESSAGE);
            cc = 0;
        }
        
          String name = nameJTF.getText().trim();
          String flast = fLastNJTF.getText().trim();
          String slast = slastNJTF.getText().trim();
          String movil = movilJTF.getText().trim();
          String tel = houseJTF.getText().trim();
          
          boolean cond = !name.equals("") && 
                         !flast.equals("") && !slast.equals("") &&
                         !movil.equals("") && !(cc == 0);
          if(cond){
              controlador.guardarPersona(cc, name, flast, slast, movil, tel);
              CancelarJBActionPerformed(null);
          }else
              JOptionPane.showMessageDialog(this, "Todos Los Campos Con * Son Obligatorios", "Error",JOptionPane.ERROR_MESSAGE);          
    }//GEN-LAST:event_enviarJBActionPerformed

    private void ccJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccJTFActionPerformed

    private void CancelarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarJBActionPerformed
          ccJTF.setText("");
          nameJTF.setText("");
          fLastNJTF.setText("");
          slastNJTF.setText("");
          movilJTF.setText("");
          houseJTF.setText("");
    }//GEN-LAST:event_CancelarJBActionPerformed

    private void nameJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameJTFKeyPressed
       if(nameJTF.getText().trim().length() > 19){
           evt.consume();
       }
    }//GEN-LAST:event_nameJTFKeyPressed

    private void fLastNJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fLastNJTFKeyPressed
       if(fLastNJTF.getText().trim().length() > 19){
           evt.consume();
       }
    }//GEN-LAST:event_fLastNJTFKeyPressed

    private void slastNJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_slastNJTFKeyPressed
         if(slastNJTF.getText().trim().length() > 19){
           evt.consume();
       }
    }//GEN-LAST:event_slastNJTFKeyPressed

    private void movilJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_movilJTFKeyPressed
         if(movilJTF.getText().trim().length() > 9){
           evt.consume();
       }
    }//GEN-LAST:event_movilJTFKeyPressed

    private void houseJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_houseJTFKeyPressed
         if(fLastNJTF.getText().trim().length() > 9){
           evt.consume();
       }
    }//GEN-LAST:event_houseJTFKeyPressed

    private void ccJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccJTFKeyPressed
         if(ccJTF.getText().trim().length() > 9){
           evt.consume();
       }
    }//GEN-LAST:event_ccJTFKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarJB;
    private javax.swing.JTextField ccJTF;
    private javax.swing.JButton enviarJB;
    private javax.swing.JLabel fLastNJL;
    private javax.swing.JTextField fLastNJTF;
    private javax.swing.JTextField houseJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField movilJTF;
    private javax.swing.JLabel nameJL;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JTextField slastNJTF;
    // End of variables declaration//GEN-END:variables

}
