/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.david.prestamos.presentacion.ultils;

import co.edu.utp.isc.david.prestamos.persistencia1.Cooperativa;
import co.edu.utp.isc.david.prestamos.persistencia1.Persona;
import co.edu.utp.isc.david.prestamos.persistencia2.Controlador;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author david
 */
public class FPrestamos extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form FPrestamos
     */
    public FPrestamos() {
        initComponents();
        coop = Cooperativa.getInstance();
        coop.addObserver(this);
        coop.notificar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dispL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ccTF = new javax.swing.JTextField();
        cliConsult = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vlrJTF = new javax.swing.JTextField();
        solB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numCCB = new javax.swing.JComboBox<>();
        Simular = new javax.swing.JButton();

        jLabel1.setText("Dinero Disponible :");

        dispL.setText("0");

        jLabel3.setText("Solicitud De Prestamos");

        jLabel4.setText("CC *");

        ccTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccTFActionPerformed(evt);
            }
        });

        cliConsult.setText("jButton1");
        cliConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliConsultActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre *");

        nameTF.setEditable(false);
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        jLabel6.setText(" Valor a solicitar ");

        solB.setText("Solicitar");
        solB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solBActionPerformed(evt);
            }
        });

        cancelB.setText("Cancelar");

        jLabel2.setText("(debe ser mayor a  $ 0.00 y maximo 10.000.000 & la cantidad a solicitar debe estar disponible) ");

        jLabel7.setText("Numero De Pagos");

        numCCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6"}));
        numCCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCCBActionPerformed(evt);
            }
        });

        Simular.setText("Simular");
        Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(dispL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ccTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cliConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vlrJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCCB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(Simular))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(solB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dispL))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vlrJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numCCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Simular)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(solB))
                    .addComponent(cancelB)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cliConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliConsultActionPerformed
        if(!ccTF.getText().trim().equals("")){
              int cc = 0;
        try {
            cc = Integer.parseInt(ccTF.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "EL valor Cedula no es correcto\n"
                    + "Recuerda que solo se admiten valores numericos sin espacios entre ellos", "Error", JOptionPane.ERROR_MESSAGE);
            cc = 0;
        }
        if(cc != 0){
             p = Controlador.getInstance().consultaPorCC(cc);
            if(p != null){
                nameTF.setText(p.getNombre());
            }
            else
                JOptionPane.showMessageDialog(this, "No se encontro el cliente asegurese de que este registrado o que escribio bien la cedula", "error", JOptionPane.ERROR_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_cliConsultActionPerformed

    private void ccTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccTFActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularActionPerformed
       int numcuotas =  Integer.parseInt((String)numCCB.getSelectedItem());
       double vlr = 0;
        try {
          vlr = Double.parseDouble(vlrJTF.getText());
        } catch (Exception e) {
            vlr = 0;
        }
       
       double vlrinteres = 0.2;
       double cuota = ((vlr * vlrinteres) + vlr) / numcuotas;
       JOptionPane.showMessageDialog(this,"El valor de las  coutas es "
       + String.format("%.3f", cuota) ,"Simulador Credito",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SimularActionPerformed

    private void numCCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCCBActionPerformed
        
    }//GEN-LAST:event_numCCBActionPerformed

    private void solBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solBActionPerformed
        if(p != null){
            double dinero = 0;
            try {
               dinero = Double.parseDouble(vlrJTF.getText().trim());
            } catch (Exception e) {
                JOptionPane.showMessageDialog
                (this, "Se debe ingresar un valor aceptable, sin espacios ni puntos entre numeros"
                 , "Error",JOptionPane.ERROR_MESSAGE);
                dinero = 0;
            }
            if(dinero > 0){
                if(dinero <= 10000000){
                    if(dinero <= coop.getDineroParaPrestar()){
                          int cuotas = Integer.parseInt((String) numCCB.getSelectedItem());
                          Controlador.getInstance().Solicitud(p, dinero, cuotas);
                    }else{
                        JOptionPane.showMessageDialog
                        (this, "El Monto no debe sobrepasar el dinero disponible"
                 , "Error",JOptionPane.ERROR_MESSAGE);
                    }
                }else{    
                JOptionPane.showMessageDialog
                (this, "El Monto Sobrepasa el maximo dinero permitido en un prestamo"
                 , "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_solBActionPerformed

    private Persona p;
    private Cooperativa coop;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simular;
    private javax.swing.JButton cancelB;
    private javax.swing.JTextField ccTF;
    private javax.swing.JButton cliConsult;
    private javax.swing.JLabel dispL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTF;
    private javax.swing.JComboBox<String> numCCB;
    private javax.swing.JButton solB;
    private javax.swing.JTextField vlrJTF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
            dispL.setText(String.format("%.1f", coop.getDineroParaPrestar()));
            actualizarPantalla();
    }
    
    public void actualizarPantalla(){ 
        
SwingUtilities.updateComponentTreeUI(this);


} 
}
