/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.david.prestamos.presentacion.ultils;

import co.edu.utp.isc.david.prestamos.persistencia1.Cooperativa;
import co.edu.utp.isc.david.prestamos.persistencia2.PagosYSolicitudes;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author david
 */
public class PTime extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form PTime
     */
    public PTime() {
        coop = Cooperativa.getInstance();
        initComponents();
        coop.addObserver(this);
        coop.setControlador(new PagosYSolicitudes());
        coop.notificar();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Timebtton = new javax.swing.JButton();

        jLabel1.setText(" AAAA / MM / DD");

        Timebtton.setText(">>");
        Timebtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimebttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(Timebtton)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Timebtton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TimebttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimebttonActionPerformed
        coop.avanzarUnDia();
    }//GEN-LAST:event_TimebttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Timebtton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private Cooperativa coop;
    @Override
    public void update(Observable o, Object arg) {
        coop = (Cooperativa) o;
        Date fecha = coop.getFecha();
        jLabel1.setText((fecha.getYear() + 1900) + "/" + (fecha.getMonth()+ 1 )+ "/"  + fecha.getDate());
    }
}
